from . import widgets
from .helper_funcs import ColorType, ColorsType
from .customisation import Font
from typing import Callable, Iterable, Union, Optional, Any, ForwardRef
import typing
import numpy

import PySide6
import pyqtgraph
from pyqtgraph import mkColor
import matplotlib.colors

from .variables import Variables
from .helper_funcs import ColorType, ColorsType


var: Variables


def plot(*args, color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float, Iterable[ForwardRef('ColorsType')]] = 'y', width: int = 1, dashed: bool = False, dash_pattern: Optional[Iterable[int]] = None, connect: str | numpy.ndarray = 'auto', gradient: Optional[PySide6.QtGui.QGradient] = None, line_style: Optional[str] = None, antialias: bool = False, auto_downsample: bool = False, downsample: int = 1, downsample_method: str = 'mean', skip_finite_check: bool = False, **kwargs) -> 'PlotCurve': ...
def scatter(*args, color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float, Iterable[ForwardRef('ColorsType')]] = 'y', size: int = 7, edge_width: int = -1, edge_color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'white', pixel_mode: bool = True, downsample: int = 1, downsample_method: str = 'mean', auto_downsample: bool = False, antialias: bool = False, **kwargs) -> 'PlotCurve': ...
def errorbar(*args, x_err=None, y_err=None, color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'y', width: int = 1, errorbar_width: int = 1, beam_size: float = 0, dashed: bool = False, dash_pattern: Iterable[int] = None, connect: str = 'auto', gradient: Optional[PySide6.QtGui.QGradient] = None, line_style: Optional[str] = None, antialias: bool = False, auto_downsample: bool = False, downsample: int = 1, downsample_method: str = 'mean', skip_finite_check: bool = False, **kwargs) -> 'PlotCurve': ...
def set_xlim(x_min: float, x_max: float): ...
def set_ylim(y_min: float, y_max: float): ...
def xlim() -> tuple[float]: ...
def ylim() -> tuple[float]: ...
def legend(): ...
def set_title(text: str | typing.Any): ...
def lock_zoom(curves: 'Iterable[PlotCurve]'): ...
def subplots(nrows: int = 1, ncols: int = 1, heightratios: Optional[list[int]] = None, widthratios: Optional[list[int]] = None) -> list: ...
def remove_item(item: pyqtgraph.graphicsItems.GraphicsObject.GraphicsObject): ...
def get_gradient(cmap: Union[str, matplotlib.colors.Colormap, Iterable, dict], style: str = 'horizontal', position: Optional[Iterable] = None, extend: str = 'pad', resolution: int = 256) -> PySide6.QtGui.QGradient: ...
def get_cmap(data: Union[str, dict[float, Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float]], Iterable[Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float]]], source: str = 'matplotlib'): ...
def inf_dline(pos: float | tuple[float], angle: float = 45, color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'y', width: int = 1, dashed: bool = False, dash_pattern: Optional[Iterable[int]] = None, line_style: Optional[str] = None, movable: bool = False, bounds: Optional[Iterable[int]] = None, span: tuple = (0, 1), line_movable: Optional[bool] = None, label: bool = False, label_text: str = '{value}', label_movable: Optional[Iterable[int]] = None, label_position: float = 0.5, label_anchors: Optional[list[tuple]] = None, hover_color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'red', hover_width: int = 1, name: Optional[str] = None, **kwargs): ...
def inf_hline(pos: float | tuple[float], color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'y', width: int = 1, dashed: bool = False, dash_pattern: Optional[Iterable[int]] = None, line_style: Optional[str] = None, movable: bool = False, bounds: Optional[Iterable[int]] = None, span: tuple = (0, 1), line_movable: Optional[bool] = None, label: bool = False, label_text: str = '{value}', label_movable: Optional[Iterable[int]] = None, label_position: float = 0.5, label_anchors: Optional[list[tuple]] = None, hover_color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'red', hover_width: int = 1, name: Optional[str] = None, **kwargs): ...
def inf_vline(pos: float | tuple[float], color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'y', width: int = 1, dashed: bool = False, dash_pattern: Optional[Iterable[int]] = None, line_style: Optional[str] = None, movable: bool = False, bounds: Optional[Iterable[int]] = None, span: tuple = (0, 1), line_movable: Optional[bool] = None, label: bool = False, label_text: str = '{value}', label_movable: Optional[Iterable[int]] = None, label_position: float = 0.5, label_anchors: Optional[list[tuple]] = None, hover_color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = 'red', hover_width: int = 1, name: Optional[str] = None, **kwargs): ...
def grid(tick_spacing: Union[tuple, float, None] = None, color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float, None] = None, width: int = 1, **kwargs): ...
def plot_text(text: str, pos: Iterable[float], color: Union[PySide6.QtGui.QColor, mkColor, str, Iterable[float], float] = (0.8, 0.8, 0.8), angle: float = 0, font: Union[str, squap.customisation.Font, None] = None, font_size: Optional[int] = None, html: Optional[str] = None, text_width: Optional[int] = None, **kwargs): ...
def merge_plots(plots: Iterable[widgets.plot_widget.SubplotWidget]) -> widgets.plot_widget.SubplotWidget: ...
def set_interval(interval: float): ...
def on_refresh(func: Callable, disconnect: bool = False): ...
def on_mouse_click(func: Callable, pixel_mode: bool = False, ax: Optional[widgets.plot_widget.SubplotWidget] = None): ...
def on_mouse_move(func: Callable, pixel_mode: bool = False, ax: Optional[widgets.plot_widget.SubplotWidget] = None): ...
def get_mouse_pos(pixel_mode=False, ax: Optional[widgets.plot_widget.SubplotWidget] = None) -> tuple: ...
def on_key_press(func: Callable, accept_modifier: bool = False, modifier_arg: bool = False, event_arg: bool = False) -> Callable: ...
def add_slider(name: str, init_value: float = 1.0, min_value: float = 0.0, max_value: float = 10.0, n_ticks: int = 51, tick_interval: Optional[float] = None, only_ints: bool = False, logscale: bool = False, custom_arr: Optional[Iterable] = None, var_name: Optional[str] = None, print_value: bool = False, row: Optional[int] = None) -> 'InputTable.Slider': ...
def add_checkbox(name: str, init_value: bool = False, var_name: Optional[str] = None, print_value: bool = False, row: Optional[int] = None) -> 'InputTable.CheckBox': ...
def add_inputbox(name: str, init_value: Any = 1.0, type_func: Optional[Callable] = None, var_name: Optional[str] = None, print_value: bool = False, row: Optional[int] = None) -> 'InputTable.InputBox': ...
def add_button(name: str, func: Optional[Callable] = None, row: Optional[int] = None) -> 'InputTable.Button': ...
def add_dropdown(name: str, options: list, init_index: int = 0, option_names: Optional[Iterable[str]] = None, var_name: Optional[str] = None, print_value: bool = False, row: Optional[int] = None) -> 'InputTable.Dropdown': ...
def add_rate_slider(name: str, init_value: float = 1.0, change_rate: float = 10.0, absolute: bool = False, time_var: Optional[str] = None, custom_func: Optional[Callable] = None, var_name: Optional[str] = None, print_value: bool = False, row: Optional[int] = None) -> 'InputTable.RateSlider': ...
def link_boxes(boxes: Iterable[widgets.input_widget.Box | int], only_update_boxes: list | None = None): ...
def add_table(name: Optional[str] = None) -> widgets.input_widget.InputTable: ...
def set_active_tab(*args: int | widgets.input_widget.InputTable | str, index: int | None = None, tab: widgets.input_widget.InputTable | None = None, name: str | None = None) -> widgets.input_widget.InputTable: ...
def rename_tab(name: str, index: Optional[int] = 0, old_name: Optional[str] = None) -> widgets.input_widget.InputTable: ...
def get_all_boxes() -> list[widgets.input_widget.Box]: ...
def display_fps(update_speed: float = 0.2, get_fps: bool = False, optimized: bool = False, ax: Optional[widgets.plot_widget.SubplotWidget] = None): ...
def resize_window(width: int, height: int): ...
def benchmark(n_frames: Optional[int] = None, duration: Optional[float] = None): ...
def set_input_width_ratio(fraction: float = 0.5): ...
def set_input_partition(fraction: float = 0.3333333333333333): ...
def is_alive() -> bool: ...
def refresh(wait_interval: bool = True, call_update_funcs: bool = True): ...
def show_window(): ...
def start(): ...
def clear(): ...
def export(filename: str, widget: str = 'window'): ...
def export_video(filename: str, fps: float = 30.0, n_frames: Optional[int] = None, duration: Optional[float] = None, stop_func: Optional[Callable] = None, skip_frames: int = 0, display_window: bool = False, widget: str = 'window', save_on_close: bool = False): ...
def start_recording(filename: str, fps: float = 30.0, skip_frames: int = 0, widget: str = 'window') -> Callable: ...
def get_font(font_name: str = 'Segoe UI', font_size: Optional[int] = None, bold: bool = False, italic: bool = False, underline: bool = False, strikethrough: bool = False, overline: bool = False, kerning: bool = False, stretch: int = 100, letter_spacing: float = 0.0, word_spacing: float = 0.0, **kwargs) -> squap.customisation.Font: ...
def cmap_to_colors(cmap: Callable, N_points: int) -> numpy.ndarray: ...